# Generated by Django 2.2.5 on 2019-10-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
