# Generated by Django 2.2.5 on 2019-10-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20191001_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
