# Generated by Django 2.2.5 on 2019-10-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_auto_20191022_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file_upload',
        ),
    ]
