# Generated by Django 2.2.5 on 2019-10-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.Writing')),
            ],
        ),
    ]
